draw_set_alpha(1)
draw_set_color(#98999b)
draw_roundrect(x, y, x + sprite_width, y + sprite_height, false)
draw_set_color(#9e28b5)
draw_roundrect(x, y, x + sprite_width, y + sprite_height, true)
draw_set_color(#9e28b5)
draw_set_font(font)
draw_set_halign(fa_middle)
draw_set_valign(fa_middle)
draw_text(x + sprite_width / 2, y + sprite_height / 2, "Endless")